<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\AppSpec */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'App Specs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="app-spec-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'category_id',
            'brand_id',
            'model_id',
            'type_id',
            'trim',
            'name',
            'tagline',
            'review:ntext',
            'summary',
            'year',
            'cc_car',
            'price_off',
            'price_on',
            'rating',
            'mobil_tipe',
            'overall_length',
            'dimensi',
            'overall_width',
            'overall_height',
            'front_tread',
            'rear_tread',
            'curb_weight',
            'gross_veh_weight',
            'ground_clearance',
            'min_turning_radius',
            'boot_capacity_min',
            'boot_capacity_max',
            'towing_limit',
            'whellbase',
            'type',
            'type_2',
            'cylinder',
            'cc',
            'bore_x_stroke',
            'compression_ratio',
            'max_power',
            'max_torque',
            'fuel_system',
            'fuel_type',
            'wheel_drive',
            'max_speed_mt',
            'seratus_km_mt',
            'urban_km_ltr_mt',
            'extra_urban_km_lt_mt',
            'combined_km_lt_mt',
            'max_speed_km_at',
            'seratus_km_at',
            'urban_km_at',
            'extra_urban_km_lt_at',
            'combined_km_lt_at',
            'fuel_tank_capacity_lt',
            'type_trans',
            'gear_ratio_1',
            'gear_ratio_2',
            'gear_ratio_3',
            'gear_ratio_4',
            'gear_ratio_5',
            'gear_ratio_6',
            'gear_ratio_7',
            'gear_ratio_8',
            'gear_ratioreverse',
            'final_gear_ratio',
            'steering',
            'front_suspension',
            'rear_suspension',
            'front_break',
            'rear_break',
            'wheel_size_front',
            'alloy_wheels',
            'tire_size_front',
            'seating_person',
            'fuel_tank_capacity_lt_cap',
            'front_seat_belt_pre_tensioners',
            'child_safety_lock',
            'central_lock',
            'alarm',
            'immobiliser',
            'driver_airbag',
            'passenger_airbag',
            'front_side_airbags',
            'front_seat_belt',
            'front_seat_belt_pre_tensioners_safe',
            'rear_seat_belt',
            'rear_reflector',
            'rain_censor',
            'rear_packing_sensor',
            'anti_lock_braking_system',
            'electronic_stability_program',
            'euro_ncap_overall_rating',
            'euro_ncap_occupant_protection',
            'euro_ncap_child_protection',
            'euro_ncap_pedestrian_protection',
            'air_conditioner',
            'climate_control',
            'seat_material',
            'power_windows',
            'power_steering',
            'tilt_steering',
            'cruise_control',
            'audio_system',
            'rear_seat_entertainment_system',
            'satelite_navigation',
            'center_stack',
            'speakers',
            'seat_belt_reminder',
            'light_off_key_reminder',
            'rear_window_defogger',
            'satellite_navigation',
            'speakers_pcs',
            'door_ajar_warning_lamp',
            'rear_seat_3_row',
            'split_fold_rear_seat',
            'leather_seats',
            'foldable_grip_assist',
            'door_pocket',
            'ashtray',
            'front_head_rest',
            'rear_head_rest',
            'tachnometer',
            'seat_back_pocket',
            'front_seat_under_tray',
            'accessory_socket',
            'inside_rear_view_mirror',
            'vanity_mirror',
            'steering_wheel',
            'body_color_door_handle',
            'roof_rail',
            'manual_sunroof',
            'electric_sunroof',
            'fog_lamps',
            'front_wiper',
            'rear_wiper',
            'electric_mirrors',
            'electric_front_windows',
            'electric_rear_windows',
            'osrvm',
            'grille_chrome',
            'muffler_tail_pipe_chrome',
            'lips_front_bumper',
            'lips_rear_bumper',
            'side_skirt',
            'chmsl',
            'colors',
            'is_deleted',
            'is_update',
            'car_merk',
            'car_model',
            'counterview',
            'car_video:ntext',
            'default_image',
            'default_image_2',
        ],
    ]) ?>

</div>
